### ISSUE TITLE
Show if Item is active [Enhancement]

### ISSUE THREAD

**Issue by MelanX** [felixlpge/ExpensiveWands#1]
It would be cool if the texture would be shown as enchanted or something like that when an item is active.
eg featherfalling rod.. i don't know when it's active

**Comment by strifel** [comment]
Will add in next version

**Comment by strifel** [comment]
5a72138ef8ac6f026a13317c12206e9f84ecae3e added this.
The Durability bar will change it color from green to red if activated.

**Comment by strifel** [comment]
This will not work with very low energy. Will be fixed next Version
